# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Test Workflow

on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI

permissions: 
  id-token: write
  contents: write
  pull-requests: write
  actions: write
  checks: write
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run tests and generate code coverage XML report
      run: dotnet test --logger trx --collect:"XPlat Code Coverage"
    - name: Restore local tools
      run: dotnet tool restore
 
    - name: Generate code coverage Markdown report
      run: dotnet reportgenerator -reports:**/coverage.cobertura.xml -targetdir:./coverage -reporttypes:MarkdownSummary
     
    - name: Create check run with code coverage Markdown report
      uses: LouisBrunner/checks-action@v1.2.0
      if: always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Code coverage
        conclusion: ${{ job.status }}
        output: '{"summary":"Code coverage"}'
        output_text_description_file: coverage/Summary.md

    - name: Lint Code Base
      uses: super-linter/super-linter@v5
      env:
        VALIDATE_CSHARP: true
        VALIDATE_ALL_CODEBASE: true
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
